### ISSUE TITLE
test todo list

### ISSUE THREAD

**Issue by ptc113** [PeterChoiOrganization/studyBoost#1]
https://stackoverflow.com/questions/325906/most-used-parts-of-boost

- [ ] [lexical_cast](http://www.boost.org/doc/libs/1_65_1/doc/html/boost_lexical_cast.html)
- [ ] [split](http://www.boost.org/doc/libs/1_57_0/doc/html/boost/algorithm/split_idp151832128.html)
- [ ] regex
- [ ] filesystem
- [ ] thread
- [ ] program_options (just brilliant!)
- [ ] test (for all my unit testing needs).
- [ ] String algorithms
- [ ] String tokenizer
- [ ] format (type-safe printf style string formatting)
- [ ] [Multi-index Containers Library](http://www.boost.org/doc/libs/1_37_0/libs/multi_index/doc/index.html)
- [ ] BOOST_STATIC_ASSERT
- [ ] random
- [ ] asio
- [ ] circular_buffer
